
build:
  os: ubuntu-22.04
  tools:
    python: "3.6"
  

# Build documentation in the "docs/" directory with Sphinx
sphinx:
   builder: html
   configuration: docs/conf.py
   fail_on_warning: true

python:
   install:
      - requirements: requirements.txt

