
build:
  os: ubuntu-22.04
  tools:
    python: "3.6"
  

# Build documentation in the "docs/" directory with Sphinx
sphinx:
   configuration: docs/conf.py


python:
   install:
      - requirements: requirements.txt

script:
    - "sphinx-build -qnN docs docs/_build/html"
